services:
  db:
    # postgresql://yak:password@localhost:5432/yakdb?sslmode=disable
    image: postgres:13.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: yak
      POSTGRES_DB: yakdb
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
